import type {
  DynastyEvent,
  DynastyPreview,
  EmperorPreview,
  ReignEraPreview,
} from '../domain/historyTypes'

export type { ReignEraPreview } from '../domain/historyTypes'

export const dynasties: readonly DynastyPreview[] = [
  { id: 'tang', name: '唐', years: '618—907', summary: '21 位皇帝 · 63 个年号' },
  { id: 'song', name: '宋', years: '960—1279', summary: '18 位皇帝 · 57 个年号' },
  { id: 'yuan', name: '元', years: '1279—1368', summary: '11 位皇帝 · 16 个年号' },
  { id: 'ming', name: '明', years: '1368—1644', summary: '16 位皇帝 · 17 个年号' },
  { id: 'qing', name: '清', years: '1644—1912', summary: '12 位皇帝 · 12 个年号' },
]

export const mingEmperors: EmperorPreview[] = [
  { id: 'taizu', name: '朱元璋', title: '太祖', years: '1368—1398', duration: '31 年', eras: ['洪武'] },
  { id: 'huidi', name: '朱允炆', title: '惠帝', years: '1399—1402', duration: '4 年', eras: ['建文'], note: '建文四年六月，明成祖废除建文年号。' },
  { id: 'chengzu', name: '朱棣', title: '成祖', years: '1403—1424', duration: '22 年', eras: ['永乐'] },
  { id: 'renzong', name: '朱高炽', title: '仁宗', years: '1425', duration: '1 年', eras: ['洪熙'] },
  { id: 'xuanzong', name: '朱瞻基', title: '宣宗', years: '1426—1435', duration: '10 年', eras: ['宣德'] },
  { id: 'yingzong', name: '朱祁镇', title: '英宗', years: '1436—1449 / 1457—1464', duration: '两度在位 · 22 年', eras: ['正统', '天顺'], note: '两段在位分别使用正统、天顺年号。' },
  { id: 'daizong', name: '朱祁钰', title: '代宗', years: '1450—1456', duration: '7 年', eras: ['景泰'], note: '夺门之变后，随即改元天顺。' },
  { id: 'xianzong', name: '朱见深', title: '宪宗', years: '1465—1487', duration: '23 年', eras: ['成化'] },
  { id: 'xiaozong', name: '朱佑樘', title: '孝宗', years: '1488—1505', duration: '18 年', eras: ['弘治'] },
  { id: 'wuzong', name: '朱厚照', title: '武宗', years: '1506—1521', duration: '16 年', eras: ['正德'] },
  { id: 'shizong', name: '朱厚熜', title: '世宗', years: '1522—1566', duration: '45 年', eras: ['嘉靖'] },
  { id: 'muzong', name: '朱载垕', title: '穆宗', years: '1567—1572', duration: '6 年', eras: ['隆庆'] },
  { id: 'shenzong', name: '朱翊钧', title: '神宗', years: '1573—1620', duration: '48 年', eras: ['万历'] },
  { id: 'guangzong', name: '朱常洛', title: '光宗', years: '1620', duration: '约四个月', eras: ['泰昌'] },
  { id: 'xizong', name: '朱由校', title: '熹宗', years: '1621—1627', duration: '7 年', eras: ['天启'] },
  { id: 'sizong', name: '朱由检', title: '思宗', years: '1628—1644', duration: '17 年', eras: ['崇祯'], note: '崇祯十七年三月，北京陷落，明朝正统期结束。' },
]

export const mingReignEras: ReignEraPreview[] = [
  {
    id: 'hongwu',
    name: '洪武',
    emperor: '朱元璋',
    templeName: '太祖',
    years: '1368—1398',
    duration: '31 年',
    startYear: 1368,
    endYear: 1398,
    note: '三十一年闰五月明惠帝即位后沿用。',
  },
  {
    id: 'jianwen',
    name: '建文',
    emperor: '朱允炆',
    templeName: '惠帝',
    years: '1399—1402',
    duration: '4 年',
    startYear: 1399,
    endYear: 1402,
    note: '四年六月明成祖废除建文年号，复称洪武三十五年。',
  },
  {
    id: 'yongle',
    name: '永乐',
    emperor: '朱棣',
    templeName: '成祖',
    years: '1403—1424',
    duration: '22 年',
    startYear: 1403,
    endYear: 1424,
    note: '二十二年八月明仁宗即位后沿用。',
  },
  {
    id: 'hongxi',
    name: '洪熙',
    emperor: '朱高炽',
    templeName: '仁宗',
    years: '1425',
    duration: '1 年',
    startYear: 1425,
    endYear: 1425,
    note: '元年六月明宣宗即位后沿用。',
  },
  {
    id: 'xuande',
    name: '宣德',
    emperor: '朱瞻基',
    templeName: '宣宗',
    years: '1426—1435',
    duration: '10 年',
    startYear: 1426,
    endYear: 1435,
    note: '十年正月明英宗即位后沿用。',
  },
  {
    id: 'zhengtong',
    name: '正统',
    emperor: '朱祁镇',
    templeName: '英宗',
    years: '1436—1449',
    duration: '14 年',
    startYear: 1436,
    endYear: 1449,
    note: '十四年九月明代宗即位后沿用。',
  },
  {
    id: 'jingtai',
    name: '景泰',
    emperor: '朱祁钰',
    templeName: '代宗',
    years: '1450—1456',
    duration: '7 年',
    startYear: 1450,
    endYear: 1456,
    note: '夺门之变后随即改元。',
  },
  {
    id: 'tianshun',
    name: '天顺',
    emperor: '朱祁镇',
    templeName: '英宗',
    years: '1457—1464',
    duration: '8 年',
    startYear: 1457,
    endYear: 1464,
    note: '八年正月明宪宗即位后沿用。',
  },
  {
    id: 'chenghua',
    name: '成化',
    emperor: '朱见深',
    templeName: '宪宗',
    years: '1465—1487',
    duration: '23 年',
    startYear: 1465,
    endYear: 1487,
    note: '二十三年九月明孝宗即位后沿用。',
  },
  {
    id: 'hongzhi',
    name: '弘治',
    emperor: '朱佑樘',
    templeName: '孝宗',
    years: '1488—1505',
    duration: '18 年',
    startYear: 1488,
    endYear: 1505,
    note: '十八年五月明武宗即位后沿用。',
  },
  {
    id: 'zhengde',
    name: '正德',
    emperor: '朱厚照',
    templeName: '武宗',
    years: '1506—1521',
    duration: '16 年',
    startYear: 1506,
    endYear: 1521,
    note: '十六年四月明世宗即位后沿用。',
  },
  {
    id: 'jiajing',
    name: '嘉靖',
    emperor: '朱厚熜',
    templeName: '世宗',
    years: '1522—1566',
    duration: '45 年',
    startYear: 1522,
    endYear: 1566,
    note: '仓库来源表未附额外的年号交接说明。',
  },
  {
    id: 'longqing',
    name: '隆庆',
    emperor: '朱载垕',
    templeName: '穆宗',
    years: '1567—1572',
    duration: '6 年',
    startYear: 1567,
    endYear: 1572,
    note: '六年六月明神宗即位后沿用。',
  },
  {
    id: 'wanli',
    name: '万历',
    emperor: '朱翊钧',
    templeName: '神宗',
    years: '1573—1620',
    duration: '48 年',
    startYear: 1573,
    endYear: 1620,
    note: '四十八年八月明光宗即位，改元泰昌。',
  },
  {
    id: 'taichang',
    name: '泰昌',
    emperor: '朱常洛',
    templeName: '光宗',
    years: '1620',
    duration: '约四个月',
    startYear: 1620,
    endYear: 1620,
    note: '元年九月明熹宗即位后沿用。',
  },
  {
    id: 'tianqi',
    name: '天启',
    emperor: '朱由校',
    templeName: '熹宗',
    years: '1621—1627',
    duration: '7 年',
    startYear: 1621,
    endYear: 1627,
    note: '七年八月明思宗即位后沿用。',
  },
  {
    id: 'chongzhen',
    name: '崇祯',
    emperor: '朱由检',
    templeName: '思宗',
    years: '1628—1644',
    duration: '17 年',
    startYear: 1628,
    endYear: 1644,
    note: '十七年三月十八日李自成攻陷北京，次日拂晓明思宗自缢，明朝灭亡。',
  },
]

export const mingDynastyEvents: DynastyEvent[] = [
  {
    year: '1368',
    title: '明朝建立',
    description: '朝代自称边界与本原型采用的正统期都从 1368 年开始。',
  },
  {
    year: '1402',
    title: '建文纪年中止',
    description: '建文四年六月，明成祖废除建文年号，复称洪武三十五年。',
  },
  {
    year: '1457',
    title: '夺门之变',
    description: '明英宗第二段在位开始，随即改元天顺。',
  },
  {
    year: '1644',
    title: '北京陷落',
    description: '崇祯十七年三月十八日李自成攻陷北京，次日明思宗自缢，明朝正统期结束。',
  },
]
