schemaVersion: 1
enabledWorkflows:
  - debugging
  - simulator
  - simulator-management
  - swift-package
  - ui-automation
debug: true
sentryDisabled: false
setupPreferences:
  platforms:
    - iOS
sessionDefaults:
  projectPath: ChineseCalendar.xcodeproj
  scheme: ChineseCalendar-iOS
  simulatorId: 16A9CAA7-45CE-46D5-8915-F61531FC617C
  simulatorName: chinesedate iPhone 18 Pro Max (885f)
