#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "../..");
const schemasDirectory = path.join(repositoryRoot, "Data/Schemas");
const tsOutputPath = path.join(repositoryRoot, "Scripts/DataAdmin/shared/generated/schema-types.ts");
const swiftOutputPath = path.join(
  repositoryRoot,
  "Scripts/BuildChineseCalendarSeedStore/Sources/ChineseCalendarSeedStoreBuilder/Generated/SwiftDataImportRecords.swift"
);

function usage() {
  return `
Usage: Scripts/DataSchemas/generate_schema_artifacts.mjs [options]

Options:
  --check       Fail if generated artifacts are not up to date.
  --help        Print this help.
`;
}

function parseArguments(argv) {
  const options = { check: false };
  for (const argument of argv) {
    switch (argument) {
      case "--check":
        options.check = true;
        break;
      case "--help":
      case "-h":
        console.log(usage().trim());
        process.exit(0);
      default:
        throw new Error(`Unknown argument: ${argument}`);
    }
  }
  return options;
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  const schemas = await loadSchemas();
  const ts = generateTypeScript(schemas);
  const swift = generateSwift(schemas);

  await writeOrCheck(tsOutputPath, ts, options.check);
  await writeOrCheck(swiftOutputPath, swift, options.check);

  if (!options.check) {
    console.log(`Generated ${path.relative(repositoryRoot, tsOutputPath)}`);
    console.log(`Generated ${path.relative(repositoryRoot, swiftOutputPath)}`);
  }
}

async function loadSchemas() {
  const files = (await readdir(schemasDirectory))
    .filter((fileName) => fileName.endsWith(".schema.json"))
    .sort();
  const schemas = [];
  for (const fileName of files) {
    const filePath = path.join(schemasDirectory, fileName);
    const schema = JSON.parse(await readFile(filePath, "utf8"));
    schemas.push({ fileName, schema });
  }
  return schemas;
}

async function writeOrCheck(filePath, content, check) {
  if (check) {
    let current = null;
    try {
      current = await readFile(filePath, "utf8");
    } catch {
      throw new Error(`Generated file is missing: ${path.relative(repositoryRoot, filePath)}`);
    }

    if (current !== content) {
      throw new Error(
        `Generated file is stale: ${path.relative(repositoryRoot, filePath)}. ` +
          "Run Scripts/DataSchemas/generate_schema_artifacts.swift."
      );
    }
    return;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

function generateTypeScript(schemas) {
  const declarations = [];
  const aliases = collectTypeScriptAliases(schemas);
  const emitted = new Set();
  for (const entry of schemas) {
    emitTypeScriptSchema(entry.schema, declarations, emitted);
  }
  trimTrailingBlankLines(declarations);

  return [
    "// Generated by Scripts/DataSchemas/generate_schema_artifacts.mjs. Do not edit by hand.",
    "",
    ...aliases,
    aliases.length > 0 ? "" : null,
    ...declarations
  ].filter((line) => line !== null).join("\n") + "\n";
}

function collectTypeScriptAliases(schemas) {
  const aliases = new Map();
  for (const { schema } of schemas) {
    collectAliasesFromSchema(schema, aliases);
  }

  return [...aliases.entries()].sort(([lhs], [rhs]) => lhs.localeCompare(rhs)).map(([name, values]) => {
    return `export type ${name} = ${values.map((value) => JSON.stringify(value)).join(" | ")};`;
  });
}

function collectAliasesFromSchema(schema, aliases) {
  const tsType = schema["x-codegen"]?.tsType;
  if (tsType && Array.isArray(schema.enum)) {
    const current = aliases.get(tsType);
    const values = schema.enum.join("\u0000");
    if (current && current.join("\u0000") !== values) {
      throw new Error(`Conflicting TypeScript alias values for ${tsType}.`);
    }
    aliases.set(tsType, schema.enum);
  }

  for (const propertySchema of Object.values(schema.properties ?? {})) {
    collectAliasesFromSchema(propertySchema, aliases);
  }
  for (const definition of Object.values(schema.$defs ?? {})) {
    collectAliasesFromSchema(definition, aliases);
  }
  for (const option of schema.anyOf ?? []) {
    collectAliasesFromSchema(option, aliases);
  }
}

function emitTypeScriptSchema(schema, declarations, emitted) {
  emitTypeScriptSchemaWithRoot(schema, schema, declarations, emitted);
}

function emitTypeScriptSchemaWithRoot(schema, rootSchema, declarations, emitted) {
  for (const definition of Object.values(schema.$defs ?? {})) {
    emitTypeScriptSchemaWithRoot(definition, rootSchema, declarations, emitted);
  }

  const typeName = schema["x-codegen"]?.typeName;
  if (!typeName || emitted.has(typeName)) {
    return;
  }

  emitted.add(typeName);
  declarations.push(`export interface ${typeName} {`);
  for (const [propertyName, propertySchema] of Object.entries(schema.properties ?? {})) {
    declarations.push(`  ${propertyName}: ${typeScriptType(propertySchema, rootSchema)};`);
  }
  declarations.push("}", "");
}

function typeScriptType(schema, rootSchema) {
  if (schema["x-codegen"]?.tsType) {
    return schema["x-codegen"].tsType;
  }

  const referenced = referencedDefinition(schema, rootSchema);
  if (referenced) {
    return typeScriptTypeName(referenced);
  }

  if (Array.isArray(schema.enum)) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (Array.isArray(schema.type)) {
    return schema.type.map((typeName) => typeScriptPrimitive(typeName)).join(" | ");
  }

  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf.map((option) => typeScriptType(option, rootSchema)).join(" | ");
  }

  return typeScriptPrimitive(schema.type);
}

function typeScriptPrimitive(typeName) {
  switch (typeName) {
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      throw new Error(`Unsupported TypeScript schema type: ${typeName}`);
  }
}

function generateSwift(schemas) {
  const declarations = [];
  const emitted = new Set();
  for (const entry of schemas) {
    emitSwiftSchema(entry.schema, declarations, emitted);
  }
  trimTrailingBlankLines(declarations);

  return [
    "// Generated by Scripts/DataSchemas/generate_schema_artifacts.mjs. Do not edit by hand.",
    "import ChineseCalendarCore",
    "import ChineseCalendarPersistence",
    "import Foundation",
    "",
    ...declarations
  ].join("\n") + "\n";
}

function trimTrailingBlankLines(lines) {
  while (lines.at(-1) === "") {
    lines.pop();
  }
}

function emitSwiftSchema(schema, declarations, emitted) {
  emitSwiftSchemaWithRoot(schema, schema, declarations, emitted);
}

function emitSwiftSchemaWithRoot(schema, rootSchema, declarations, emitted) {
  for (const definition of Object.values(schema.$defs ?? {})) {
    emitSwiftSchemaWithRoot(definition, rootSchema, declarations, emitted);
  }

  const typeName = schema["x-codegen"]?.typeName;
  if (!typeName || emitted.has(typeName)) {
    return;
  }

  emitted.add(typeName);
  declarations.push(`struct ${typeName}: Decodable {`);
  for (const [propertyName, propertySchema] of Object.entries(schema.properties ?? {})) {
    declarations.push(`    let ${propertyName}: ${swiftType(propertySchema, rootSchema)}`);
  }
  declarations.push("}", "");
}

function swiftType(schema, rootSchema) {
  if (schema["x-codegen"]?.swiftType) {
    return optionalSwiftType(schema["x-codegen"].swiftType, schema);
  }

  const referenced = referencedDefinition(schema, rootSchema);
  if (referenced) {
    return optionalSwiftType(typeScriptTypeName(referenced), schema);
  }

  if (Array.isArray(schema.enum)) {
    return "String";
  }

  if (Array.isArray(schema.anyOf)) {
    const nonNullOptions = schema.anyOf.filter((option) => option.type !== "null");
    const hasNull = nonNullOptions.length !== schema.anyOf.length;
    if (nonNullOptions.length !== 1 || !hasNull) {
      throw new Error(`Unsupported Swift anyOf: ${JSON.stringify(schema)}`);
    }
    return `${swiftType(nonNullOptions[0], rootSchema)}?`;
  }

  if (Array.isArray(schema.type)) {
    const nonNullTypes = schema.type.filter((typeName) => typeName !== "null");
    const hasNull = nonNullTypes.length !== schema.type.length;
    if (nonNullTypes.length !== 1 || !hasNull) {
      throw new Error(`Unsupported Swift union type: ${schema.type.join(", ")}`);
    }
    return `${swiftPrimitive(nonNullTypes[0])}?`;
  }

  return swiftPrimitive(schema.type);
}

function swiftPrimitive(typeName) {
  switch (typeName) {
    case "integer":
      return "Int";
    case "string":
      return "String";
    case "boolean":
      return "Bool";
    default:
      throw new Error(`Unsupported Swift schema type: ${typeName}`);
  }
}

function optionalSwiftType(typeName, schema) {
  if (Array.isArray(schema.type) && schema.type.includes("null")) {
    return `${typeName}?`;
  }
  return typeName;
}

function referencedDefinition(schema, rootSchema) {
  if (schema.$ref) {
    return resolveReference(schema.$ref, rootSchema);
  }
  return null;
}

function resolveReference(reference, rootSchema) {
  const prefix = "#/$defs/";
  if (!reference.startsWith(prefix)) {
    throw new Error(`Unsupported reference: ${reference}`);
  }
  const definitionName = reference.slice(prefix.length);
  const definition = rootSchema.$defs?.[definitionName];
  if (!definition) {
    throw new Error(`Missing schema definition: ${definitionName}`);
  }
  return definition;
}

function typeScriptTypeName(schema) {
  const typeName = schema["x-codegen"]?.typeName;
  if (!typeName) {
    throw new Error(`Schema object is missing x-codegen.typeName: ${JSON.stringify(schema)}`);
  }
  return typeName;
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
